name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Specify the version of .NET you are using

    - name: Restore dependencies
      run: dotnet restore ./MyApi.sln

    - name: Build
      run: dotnet build ./MyApi.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./MyApi.sln --no-build --verbosity normal